-- ========================================
-- Scene: Scene
-- Generated by SceneSerializer
-- ========================================

-- ========================================
-- CATEGORIES
-- ========================================

-- Category: Drawable
print("[Scene] Defining category: Drawable")
LoadCategory("Drawable", [[
return Category {
    shaderPath  = "",
    shader      = nil,
    texturePath = "",
    texture     = nil,
    modelPath   = "",
    model       = Asset.Model("./resources/Models/curuthers.obj")
}]])

-- Category: Transform
print("[Scene] Defining category: Transform")
LoadCategory("Transform", [[
return Category {
    Position = Vector2.new(0.0),
    Layer    = 0,
    Rotation = 0.0,
    Scale    = Vector2.new(1),
    Blingo = true
}]])

-- ========================================
-- RULES
-- ========================================

-- ========================================
-- ENTITIES
-- ========================================

-- Entity1 (id=1)
print("[Scene] Creating entity: Entity1")
local e1 = scene:addEntity()
scene:addToCategory(e1, "Transform")
local e1_Transform = scene:getAttributesOf(e1)["Transform"]
if e1_Transform then
    e1_Transform["Rotation"] = 0.0
    e1_Transform["Position"] = Vector2(4.65625, 0.5468749)
    e1_Transform["Layer"] = 0
    e1_Transform["Blingo"] = true
    e1_Transform["Scale"] = Vector2(1, 1)
end

scene:addToCategory(e1, "Drawable")
local e1_Drawable = scene:getAttributesOf(e1)["Drawable"]
if e1_Drawable then
    e1_Drawable["modelPath"] = "./resources/Models/curuthers.obj"
    e1_Drawable["texturePath"] = ""
    e1_Drawable["shaderPath"] = "./resources/Shaders/default/frag.fs;./resources/Shaders/default/vert.vs"
end

-- Entity0 (id=0)
print("[Scene] Creating entity: Entity0")
local e0 = scene:addEntity()
scene:addToCategory(e0, "Transform")
local e0_Transform = scene:getAttributesOf(e0)["Transform"]
if e0_Transform then
    e0_Transform["Rotation"] = 0.0
    e0_Transform["Position"] = Vector2(-6.484375, 1.28125)
    e0_Transform["Layer"] = 0
    e0_Transform["Blingo"] = true
    e0_Transform["Scale"] = Vector2(1, 1)
end

print("[Scene] Scene 'Scene' constructed successfully.")
